openapi: 3.0.0
info:
  title: Auth Service API
  description: API для сервиса авторизации
  version: 1.0.0
  contact:
    name: Support
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email пользователя
        password:
          type: string
          minLength: 6
          description: Пароль пользователя

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email пользователя
        password:
          type: string
          minLength: 6
          description: Пароль пользователя

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          description: ID пользователя
        email:
          type: string
          format: email
          description: Email пользователя
        role:
          type: string
          description: Роль пользователя
        created_at:
          type: string
          format: date-time
          description: Дата создания
        updated_at:
          type: string
          format: date-time
          description: Дата обновления

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT токен доступа
        refresh_token:
          type: string
          description: Токен для обновления
        token_type:
          type: string
          description: Тип токена
        expires_in:
          type: integer
          description: Время жизни токена в секундах

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Сообщение об ошибке

paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      description: Создает нового пользователя в системе
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Неверный формат данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Пользователь уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/login:
    post:
      summary: Авторизация пользователя
      description: Выполняет вход пользователя в систему
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Неверный формат данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неверные учетные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
