basePath: /
definitions:
  entity.ErrorResponse:
    properties:
      error:
        example: Internal server error
        type: string
    type: object
  entity.Message:
    properties:
      id:
        example: 1
        type: integer
      message:
        example: Hello, world!
        type: string
      timestamp:
        example: "2023-10-27T10:00:00Z"
        type: string
      user_id:
        example: 123
        type: integer
      username:
        example: john_doe
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a chat microservice with WebSocket support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Chat Microservice API
  version: "1.0"
paths:
  /api/v1/messages:
    get:
      consumes:
      - application/json
      description: Get a list of recent chat messages
      produces:
      - application/json
      responses:
        "200":
          description: List of messages
          schema:
            items:
              $ref: '#/definitions/entity.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Get chat messages history
      tags:
      - messages
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
